### ISSUE TITLE
lv2lint and sord_validate error during build

### ISSUE THREAD

**Issue by dvzrv** [brummer10/Xmonk.lv2#3]
When building xmonk.lv2 0.3 for Arch Linux I ran lv2lint and sord_validate on the plugin.
Both are failing though:

[xmonk.lv2-0.3-1-x86_64-check.log](https://github.com/brummer10/Xmonk.lv2/files/3907221/xmonk.lv2-0.3-1-x86_64-check.log)

**Comment by brummer10** [comment]
Hi
Thanks for the hint. 
I've pushed a update to the repository now, which should solve all errors given by lv2lint. 

regards
hermann
