### ISSUE TITLE
Do you plan to continue both Xmonks?

### ISSUE THREAD

**Issue by schnitzeltony** [brummer10/Xmonk.lv2#7]
Hi Hermann,

Background: Have decided to test builds on aarch64. Now Xmonk.lv2 fails to build and from a quick glance on the error message it looks like Xmonk needs same as [1]  (and please don't ask why it builds for Armv7 - have no idea)

So my question: Do you plan further development on XMonk and XPolymonk? If no I'd simply drop Xmonk from my builds.

[1] https://github.com/brummer10/XPolyMonk.lv2/commit/6e978f09f3040ada68c20dc7097267cc94e1bb53

**Comment by brummer10** [comment]
Hi
I'll continue to fix bugs and keep the source buildable with modern GCC's. 
So I've pushed a update for libxputty and fixed the deprecated use of the struct _ LV2UI_Descriptor.

**Comment by schnitzeltony** [comment]
You fixed it - Thanks!
